trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
    includePreviewVersions: true

- script: dotnet --version
  displayName: Check SDK

- script: dotnet restore DotNetApp.csproj
  displayName: Restore

- script: dotnet build DotNetApp.csproj --configuration Release
  displayName: Build