trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 8.x

- script: dotnet restore **/*.csproj
  displayName: Restore

- script: dotnet build **/*.csproj --configuration Release
  displayName: Build